In [2]:
import numpy as np
import pandas as pd

# Introducing Pandas Objects

### The Pandas Series Object : 1 dim array

In [3]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [4]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [5]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
data[0:2] #숫자 index는 2전인 1번 index의 값까지 보여줌

0    0.25
1    0.50
dtype: float64

In [7]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = ['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [8]:
data['a':'c'] #문자 index의 경우 'c'index까지 모든 값을 보여줌

a    0.25
b    0.50
c    0.75
dtype: float64

In [9]:
data['b']

0.5

In [10]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = [2, 5, 3, 7])
data
#이런식으로 코딩하면 헷갈리므로 특별한 이유가 있지 않은 이상 index를 차례대로 쓰는 것이 좋음

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [11]:
data[3]

0.75

In [12]:
# Pandas Series에 dictionary도 넣을수 있음

population_dict = {'California': 38332521, 'Texas': 26448193, 'New York': 19651127, 'Florida': 19552860, 'Illinois': 12882135}
population_dict

{'California': 38332521,
 'Texas': 26448193,
 'New York': 19651127,
 'Florida': 19552860,
 'Illinois': 12882135}

In [13]:
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [14]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297, 'Florida': 170312, 'Illinois': 149995}
area_dict

{'California': 423967,
 'Texas': 695662,
 'New York': 141297,
 'Florida': 170312,
 'Illinois': 149995}

In [15]:
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

### The Pandas DataFrame Object : 2 dim array

In [16]:
states = pd.DataFrame({'population': population, 'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [17]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [18]:
states.columns

Index(['population', 'area'], dtype='object')

In [19]:
states.values

array([[38332521,   423967],
       [26448193,   695662],
       [19651127,   141297],
       [19552860,   170312],
       [12882135,   149995]], dtype=int64)

In [20]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [21]:
# pandas dataframe 만들기

In [22]:
# 1)from a single series object
pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [23]:
# 2)from a list of dicts
data = [{'a': i, 'b': 2*i}
       for i in range(3)]

In [24]:
pd.Series(data)

0    {'a': 0, 'b': 0}
1    {'a': 1, 'b': 2}
2    {'a': 2, 'b': 4}
dtype: object

In [25]:
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [26]:
# 3)from a dictionary of Series object
pd.DataFrame({'population' : population, 'area': area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [27]:
# 4)from a 2-dim numpy array
pd.DataFrame(np.random.rand(3,2),
             columns=['foo','bar'],
             index=['a','b','c'])

foo       bar
a  0.386460  0.643512
b  0.377654  0.371648
c  0.174971  0.332981

### The Pandas Index Object

In [28]:
ind = pd.Index([2,3,5,7,11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [29]:
# index as immutable array
# Index in many ways operates like an array

In [30]:
ind[1]

3

In [31]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [32]:
#immutable array이기 때문에 ind[1] = 4 에러!

In [33]:
# Index as ordered set
indA = pd.Index([1,3,5,7,9])
indB = pd.Index([2,3,5,7,11])

In [34]:
indA & indB  #intersection -> 순서대로 정렬함.

Int64Index([3, 5, 7], dtype='int64')

In [35]:
indA | indB  #union -> 순서대로 정렬함.

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [36]:
indA ^ indB  #symmetric difference -> 순서대로 정렬함.

Int64Index([1, 2, 9, 11], dtype='int64')

# Data Indexing and Selection

### Data Selection in Series

In [37]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = ['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [38]:
data['b']

0.5

In [39]:
'a' in data

True

In [40]:
print(data.keys())
print(data.values)
print(data.items())
list(data.items())

Index(['a', 'b', 'c', 'd'], dtype='object')
[0.25 0.5  0.75 1.  ]


[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [41]:
data[1:3]

b    0.50
c    0.75
dtype: float64

In [42]:
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [43]:
data = pd.Series(['a', 'b', 'c'], index = [1,3,5])
data

1    a
3    b
5    c
dtype: object

In [44]:
data[1] #[index]

'a'

In [45]:
data[0] #순서라고 생각하면 안됨

KeyError: 0

In [ ]:
#data.loc

In [46]:
data.loc[1]

'a'

In [47]:
data.loc[3]

'b'

In [48]:
data.loc[5]

'c'

In [49]:
data.loc[1:2]

1    a
dtype: object

In [50]:
data.loc[2:3]

3    b
dtype: object

In [51]:
data[1:2]

3    b
dtype: object

In [52]:
data[2:3]

5    c
dtype: object

In [53]:
data[0:3]

1    a
3    b
5    c
dtype: object

In [54]:
#data.iloc

In [55]:
data.iloc[0]

'a'

In [56]:
data.iloc[1]

'b'

In [57]:
data.iloc[2]

'c'

In [58]:
data.iloc[0:1]

1    a
dtype: object

In [59]:
data.iloc[1:3]

3    b
5    c
dtype: object

In [60]:
data[1:3]

3    b
5    c
dtype: object

In [61]:
#data.iloc[순서]
#data.iloc[] == data[]

In [62]:
# Data Selection in DataFrame

In [63]:
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [64]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [65]:
states
#위에서 사용한 area, population, states 이용

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [66]:
data = states

In [67]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [68]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [69]:
data['area'] == data.area
# 두 자료의 값이 똑같은지 아닌지를 판단

California    True
Texas         True
New York      True
Florida       True
Illinois      True
Name: area, dtype: bool

In [70]:
data.area is data['area']
#두 자료가 같은지 아닌지 판단

True

In [71]:
#기존의 column을 이용하여 새로운 column을 만들 수도 있음
data['density'] = data['population']/data['area']

In [72]:
data

population    area     density
California    38332521  423967   90.413926
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763

In [73]:
data.values

array([[3.83325210e+07, 4.23967000e+05, 9.04139261e+01],
       [2.64481930e+07, 6.95662000e+05, 3.80187404e+01],
       [1.96511270e+07, 1.41297000e+05, 1.39076746e+02],
       [1.95528600e+07, 1.70312000e+05, 1.14806121e+02],
       [1.28821350e+07, 1.49995000e+05, 8.58837628e+01]])

In [74]:
#transpose
data.T

California         Texas      New York       Florida  \
population  3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07   
area        4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05   
density     9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02   

                Illinois  
population  1.288214e+07  
area        1.499950e+05  
density     8.588376e+01

In [75]:
data.values[0]

array([3.83325210e+07, 4.23967000e+05, 9.04139261e+01])

In [76]:
data

population    area     density
California    38332521  423967   90.413926
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763

In [77]:
data.iloc[:2, :3]

population    area    density
California    38332521  423967  90.413926
Texas         26448193  695662  38.018740

In [78]:
data.iloc[:3, :2]

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297

In [79]:
data.ix[:3, :'population']

C:\Users\user\Anaconda\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


population
California    38332521
Texas         26448193
New York      19651127

In [80]:
data.ix[:2, :'density']

C:\Users\user\Anaconda\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


population    area    density
California    38332521  423967  90.413926
Texas         26448193  695662  38.018740

In [82]:
data.loc[data.density > 100, ['area', 'population']]

area  population
New York  141297    19651127
Florida   170312    19552860

In [83]:
data[data.density > 100]

population    area     density
New York    19651127  141297  139.076746
Florida     19552860  170312  114.806121

In [84]:
data.iloc[0,2] = 90

In [85]:
data

population    area     density
California    38332521  423967   90.000000
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763

# Operating on Data in Pandas

In [86]:
#Ufuncs: Index Preservation
#numpy의 Ufuncs와 같이 사용

In [15]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [16]:
df = pd.DataFrame(rng.randint(0, 10, (3,4)), columns = ['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [89]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [90]:
np.sin(df + np.pi/4)

A         B         C         D
0  0.481366 -0.352855  0.348710  0.481366
1  0.997649 -0.997336 -0.600243  0.997649
2  0.997649  0.348710 -0.477482 -0.997336

In [91]:
#UFuncs: Index Alignment

In [92]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662, 'California': 423967}, name = 'area')
area

Alaska        1723337
Texas          695662
California     423967
Name: area, dtype: int64

In [93]:
population = pd.Series({'California': 38332521, 'Texas': 26448193, 'New York': 19651127}, name = 'population')
population

California    38332521
Texas         26448193
New York      19651127
Name: population, dtype: int64

In [94]:
population/area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [95]:
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [96]:
area.index & population.index

Index(['Texas', 'California'], dtype='object')

In [3]:
A = pd.Series([2, 4, 6], index = [0, 1, 2])
B = pd.Series([1, 3, 5], index = [1, 2, 3])

In [4]:
A

0    2
1    4
2    6
dtype: int64

In [5]:
B

1    1
2    3
3    5
dtype: int64

In [6]:
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [7]:
A.add(B)

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [8]:
A.add(B, fill_value = 0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [9]:
A.add(B, fill_value = 1)

0    3.0
1    5.0
2    9.0
3    6.0
dtype: float64

In [10]:
A.add(B, fill_value = 2)

0    4.0
1    5.0
2    9.0
3    7.0
dtype: float64

In [17]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)), columns = list('AB'))
A

A   B
0  1  11
1  5   1

In [18]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)), columns = list('BAC'))
B

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [19]:
A + B

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [20]:
A.add(B)

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [21]:
A.add(B, fill_value = 0)

A     B    C
0   1.0  15.0  9.0
1  13.0   6.0  0.0
2   2.0   9.0  6.0

In [110]:
A

A   B
0  1  11
1  5   1

In [111]:
fill = A.stack().mean() #== (1 + 11 + 5 + 1)/4
fill

4.5

In [112]:
A.add(B, fill_value = fill)

A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

In [113]:
# Ufuncs: Operations Between DataFrame and Series

In [114]:
A = rng.randint(10, size = (3, 4))
A

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [115]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-1, -2,  2,  4],
       [ 3, -7,  1,  4]])

In [116]:
pd.DataFrame(A - A[0], columns = list('QRST'))

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [117]:
df = pd.DataFrame(A, columns = list('QRST'))
df

Q  R  S  T
0  3  8  2  4
1  2  6  4  8
2  6  1  3  8

In [118]:
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

# Handling Missing Data

In [119]:
# Missing Data in Pandas

In [120]:
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

In [121]:
#None: Pythonic missing data -> cannot used for any arbitrary Numpy/Pandas array, but only in arrays with data type 'object'

In [122]:
#NaN: Missing numerical data

In [123]:
vals2 = np.array([1, np.nan, 3, 4])
vals2

array([ 1., nan,  3.,  4.])

In [124]:
#Nan이 섞여있으면 double 형태로 받음

In [125]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [126]:
x = pd.Series(range(2), dtype = int)
x

0    0
1    1
dtype: int32

In [127]:
x[0] = None
x

0    NaN
1    1.0
dtype: float64

In [128]:
# Operating on Null Values

In [129]:
data = pd.Series([1, np.nan, 'hello', None])
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [130]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [131]:
data[data.isnull()]

1     NaN
3    None
dtype: object

In [132]:
data.notnull()

0     True
1    False
2     True
3    False
dtype: bool

In [133]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [134]:
data.dropna()

0        1
2    hello
dtype: object

In [135]:
df = pd.DataFrame([[1, np.nan, 2],
                  [2, 3, 5],
                  [np.nan, 4, 6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [136]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [137]:
df.dropna(axis = 'columns')

2
0  2
1  5
2  6

In [138]:
df.dropna(axis = 0)

0    1  2
1  2.0  3.0  5

In [139]:
df. dropna(axis = 1)

2
0  2
1  5
2  6

In [140]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [141]:
df.dropna(axis = 'columns', how = 'all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [142]:
df.dropna(axis = 'rows', thresh = 3)

0    1  2   3
1  2.0  3.0  5 NaN

In [143]:
data = pd.Series([1, np.nan, 2, None, 3], index = list('abcde'))


In [144]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [145]:
data.fillna(10)

a     1.0
b    10.0
c     2.0
d    10.0
e     3.0
dtype: float64

In [146]:
data.fillna('a')

a    1
b    a
c    2
d    a
e    3
dtype: object

In [147]:
data.fillna(method = 'ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [148]:
data.fillna(method = 'bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64